void() monster_tarbaby =
{
	self.classname = "monster_army";
	monster_army();
};

void() monster_fish =
{
	self.classname = "monster_wizard";
	monster_wizard();
};

// dwell monster replacement
void() monster_kamikaze = 
{
	self.classname = "monster_knight";
	monster_knight();
};

void() monster_excavator =
{
	self.classname = "monster_wizard";
	monster_wizard();
};

void() monster_brute =
{
	self.classname = "monster_shalrath";
	monster_shalrath();
};